# Generated by Django 6.1 on 2026-08-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=100)),
                ('estado_conservacao', models.CharField(max_length=50)),
                ('responsavel', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
