# Generated by Django 6.1 on 2026-08-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_livro_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
