# Generated by Django 6.1 on 2026-09-09 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_livro_ativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_interesse', models.DateTimeField(auto_now_add=True)),
                ('interessado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interesses_em_livros', to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interesses', to='core.livro')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('livro', 'interessado'), name='interesse_unico_por_livro_usuario')],
            },
        ),
    ]
