# Generated by Django 6.1 on 2026-09-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_interesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesse',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITO', 'Aceito'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=20),
        ),
    ]
