# Generated by Django 6.1 on 2026-09-14 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_interesse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='situacao',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EMPRESTADO', 'Emprestado'), ('RESERVADO', 'Reservado')], default='DISPONIVEL', max_length=20),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('CANCELADA', 'Cancelada'), ('CONCLUIDA', 'Concluída')], default='ATIVA', max_length=20)),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('interessado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='core.interesse')),
            ],
        ),
    ]
