# Generated by Django 6.1 on 2026-09-15 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_livro_situacao_reserva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='interessado',
            new_name='interesse',
        ),
    ]
