# Generated by Django 6.1 on 2026-09-16 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_interessado_reserva_interesse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('DEVOLVIDO', 'Devolvido')], default='ATIVO', max_length=20)),
                ('emprestado_em', models.DateTimeField(auto_now_add=True)),
                ('devolvido_em', models.DateTimeField(blank=True, null=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimo', to='core.reserva')),
            ],
        ),
    ]
