# Generated by Django 6.1 on 2026-09-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_emprestimo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='encerrada_em',
            new_name='data_aprovacao',
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_encerramento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_retirada_prevista',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='situacao',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('RESERVADO', 'Reservado'), ('EMPRESTADO', 'Emprestado')], default='DISPONIVEL', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada'), ('CANCELADA', 'Cancelada'), ('NAO_RETIRADA', 'Não retirada'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20),
        ),
    ]
