# Generated by Django 6.1 on 2026-09-19 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_encerrada_em_reserva_data_aprovacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-data_reserva']},
        ),
        migrations.AddField(
            model_name='reserva',
            name='cancelada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_RESPONSAVEL', 'Aguardando responsável'), ('AGUARDANDO_INTERESSADO', 'Aguardando interessado'), ('APROVADA', 'Aprovada'), ('CANCELADA', 'Cancelada'), ('NAO_RETIRADA', 'Não retirada'), ('CONCLUIDA', 'Concluída')], default='AGUARDANDO_RESPONSAVEL', max_length=30),
        ),
        migrations.CreateModel(
            name='PropostaReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateField()),
                ('autor', models.CharField(choices=[('INTERESSADO', 'Interessado'), ('RESPONSAVEL', 'Responsável')], max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='core.reserva')),
            ],
            options={
                'ordering': ['criada_em'],
            },
        ),
    ]
