# Generated by Django 6.1 on 2026-09-21 22:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_reserva_options_reserva_cancelada_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='capa'),
        ),
    ]
